dist: trusty
language: node_js
sudo: required
node_js:
  - '6.9.4'
cache:
  directories:
  - node_modules
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install make
  - sudo apt-get -y install libsasl2-dev
